name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup mpi
      run: sudo apt-get install libcr-dev mpich2 mpich2-doc
    - name: make build
      run: make build
    - name: run build
      run: ./main
