name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v3
    - uses: mpi4py/setup-mpi@v1      

    - run: mpicc Huita.cpp -o helloworld
    - run: mpiexec -n 10 ./helloworld
        
    - name: make build
      run: make build
    - name: run build
      run: ./main
