name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Microsoft MPI
      id:   setup2
      uses: ./
      with:
        mpi: microsoft

    - run: test ${{ steps.setup1.outputs.mpi }} == intelmpi
    - run: test ${{ steps.setup2.outputs.mpi }} == msmpi
        

    - run: mpicc Huita.cpp -o helloworld
    - run: mpiexec -n 10 ./helloworld
        
    - name: make build
      run: make build
    - name: run build
      run: ./main
