name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    
    - name: Setup Intel MPI
      id:   setup1
      uses: ./
      with:
        mpi: intel

    - name: Setup Microsoft MPI
      id:   setup2
      uses: ./
      with:
        mpi: microsoft
        

    - run: test ${{ steps.setup1.outputs.mpi }} == intelmpi
    - run: test ${{ steps.setup2.outputs.mpi }} == msmpi
    - run: mpicc Huita.cpp -o helloworld
    - run: mpiexec -n 10 ./helloworld
        
    - uses: actions/checkout@v3
    - name: setup mpi
      run: mpicc MPI.cpp
    - name: make build
      run: make build
    - name: run build
      run: ./main
