name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3   

    - run: sudo apt install openmpi-bin openmpi-dev openmpi-common openmpi-doc libopenmpi-dev
    - run: mpicxx Huita.cpp -o helloworld
    - run: mpiexec -n 10 ./helloworld
        
    - name: make build
      run: make build
    - name: run build
      run: ./main
