name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    - uses: mpi4py/setup-mpi@v1
    - run: mpicc Huita.cpp -o helloworld
    - run: mpiexec -n 10 ./helloworld
        
    - uses: actions/checkout@v3
    - name: setup mpi
      run: mpicc MPI.cpp
    - name: make build
      run: make build
    - name: run build
      run: ./main
